name: pub_serve_proxy
version: 3.0.0
description: A reverse proxy for pub serve build with Angel 3 framework
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
  angel3_production: ^6.0.0
  angel3_proxy: ^6.0.0
  angel3_static: ^6.0.0
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
