name: pub_serve_proxy
version: 1.0.0
description: An application for serving pub through proxy
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.10.0 <3.0.0'
homepage: https://github.com/dukefirehawk/angel3-examples
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_production: ^1.0.0-alpha
  angel_proxy: ^2.0.0
  angel_static: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0