name: pub_serve_proxy
version: 3.0.0
description: A reverse proxy for pub serve build with Angel 3 framework
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_framework: ^8.0.0
  angel3_production: ^8.0.0
  angel3_proxy: ^8.0.0
  angel3_static: ^8.0.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^3.2.0
  lints: ^2.1.0
