name: pub_serve_proxy
version: 2.1.0
description: An application for serving pub through proxy
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.1.0
  angel3_production: ^3.1.0
  angel3_proxy: ^4.0.0
  angel3_static: ^4.0.0
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
