name: pub_serve_proxy
version: 2.1.0
description: A reverse proxy for pub serve build with Angel 3 framework
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.1.0
  angel3_production: ^3.1.0
  angel3_proxy: ^4.0.0
  angel3_static: ^4.0.0
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
