name: backend
version: 4.0.0
description: A flutter backend
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  angel3_websocket: ^7.0.0
  common:
    path: ../common
dev_dependencies:
  lints: ^2.0.0
