name: backend
version: 3.0.0
description: A flutter backend
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
  angel3_websocket: ^6.0.0
  common:
    path: ../common
dev_dependencies:
  lints: ^1.0.0
