name: yewtube
version: 3.0.0
description: A video streaming application.
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_configuration: ^6.0.0
  angel3_file_service: ^6.0.0
  angel3_framework: ^6.0.0
  angel3_jael: ^6.0.0
  angel3_serialize: ^6.0.0
  angel3_static: ^6.0.0
  angel3_validate: ^6.0.0
  uuid: ^3.0.0
  collection: ^1.15.0
dev_dependencies:
  angel3_serialize_generator: ^6.0.0
  build_runner: ^2.0.0
  lints: ^1.0.0
