name: yewtube
version: 4.0.0
description: A video streaming application.
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  angel3_configuration: ^7.0.0
  angel3_file_service: ^7.0.0
  angel3_framework: ^7.0.0
  angel3_jael: ^7.0.0
  angel3_serialize: ^7.0.0
  angel3_static: ^7.0.0
  angel3_validate: ^7.0.0
  uuid: ^3.0.0
  collection: ^1.15.0
dev_dependencies:
  angel3_serialize_generator: ^7.0.0
  build_runner: ^2.0.0
  lints: ^2.0.0
