name: auth
version: 2.1.0
description: A simple authentication demo application
publish_to: none
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_framework: ^4.1.0
  angel3_static: ^4.1.0
  dbcrypt: ^2.0.0
dev_dependencies:
  lints: ^1.0.0
