name: auth
version: 2.0.1
description: A simple Auth application
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_framework: ^4.0.0
  angel3_static: ^4.0.0
  dbcrypt: ^2.0.0
dev_dependencies:
  pedantic: ^1.11.0
