name: hello_angel
version: 3.0.0
description: A simple Hello World application in Angel3
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
    sdk: '>=2.16.0 <3.0.0'
homepage: https://github.com/dukefirehawk/angel3-examples
dependencies:
    angel3_framework: ^6.0.0
dev_dependencies:
    lints: ^1.0.0
