name: yewtube
version: 2.0.0
description: A video streaming application.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_configuration: ^4.0.0
  angel3_file_service: ^4.0.0
  angel3_framework: ^4.0.0
  angel3_jael: ^4.0.0
  angel3_serialize: ^4.0.0
  angel3_static: ^4.0.0
  angel3_validate: ^4.0.0
  uuid: ^3.0.0
  collection: ^1.15.0
dev_dependencies:
  angel3_serialize_generator: ^4.0.0
  build_runner: ^2.0.0
  pedantic: ^1.11.0
