name: common
version: 3.0.0
description: A flutter common
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_model: ^8.0.0
  angel3_serialize: ^8.0.0
dev_dependencies:
  angel3_serialize_generator: ^8.0.0
  build_runner: ^2.4.0
  lints: ^2.1.0
 