name: common
version: 1.0.0
description: A flutter common
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.10.0 <3.0.0'
homepage: https://github.com/dukefirehawk/angel3-examples
dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0