name: common
version: 2.1.0
description: A flutter common
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_model: ^3.0.0
  angel3_serialize: ^4.0.0
dev_dependencies:
  angel3_serialize_generator: ^4.2.0
  build_runner: ^2.0.0
  lints: ^1.0.0
 