name: dchan
version: 2.1.0
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.3
  angel3_configuration: ^4.0.0
  angel3_framework: ^4.1.0
  angel3_jael: ^4.1.0
  angel3_migration: ^4.0.0
  angel3_orm: ^4.0.0
  angel3_orm_postgres: ^3.0.0
  angel3_serialize: ^4.0.0
  angel3_production: ^3.1.0
  angel3_static: ^4.0.0
  angel3_validate: ^4.0.0
  filesize: ^2.0.0
  markdown: ^4.0.0
  optional: ^6.0.0
dev_dependencies:
  angel3_hot: ^4.2.0
  angel3_migration_runner: ^4.0.0
  angel3_orm_generator: ^4.1.0
  angel3_serialize_generator: ^4.2.0
  angel3_test: ^4.0.2
  belatuk_pretty_logging: ^4.0.0
  build_runner: ^2.0.4
  io: ^1.0.0
  lints: ^1.0.0
  test: ^1.17.5

