name: dchan
version: 5.0.0
description: An app that's going to be amazing pretty soon.
publish_to: none
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  angel3_auth: ^8.0.0
  angel3_configuration: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_jael: ^8.0.0
  angel3_migration: ^8.0.0
  angel3_orm: ^8.0.0
  angel3_orm_postgres: ^8.0.0
  angel3_serialize: ^8.0.0
  angel3_production: ^8.0.0
  angel3_static: ^8.0.0
  angel3_validate: ^8.0.0
  angel3_hot: ^8.0.0
  angel3_migration_runner: ^8.0.0
  belatuk_pretty_logging: ^6.0.0
  postgres: ^3.0.0
  filesize: ^2.0.0
  markdown: ^7.1.0
  optional: ^6.0.0
  file: ^7.0.1
  logging: ^1.3.0
  angel3_container: ^8.3.0
dev_dependencies:
  angel3_orm_generator: ^8.0.0
  angel3_serialize_generator: ^8.0.0
  angel3_test: ^8.0.0
  build_runner: ^2.0.4
  lints: ^5.0.0
  test: ^1.24.0

