name: star_wars
version: 2.1.0
description: A star wars application in graphQL
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_graphql: ^2.1.0
  angel3_configuration: ^4.0.0
  angel3_jael: ^4.0.0
  angel3_production: ^3.0.0
  angel3_serialize: ^4.0.0
  angel3_container: ^3.0.0
  angel3_static: ^4.0.0
  io: ^1.0.0
dev_dependencies:
  angel3_hot: ^4.2.0
  angel3_serialize_generator: ^4.2.0
  belatuk_pretty_logging: ^4.0.0
  graphql_generator2: ^2.2.0
  build_runner: ^2.0.0
  lints: ^1.0.0
#dependency_overrides:
#  angel3_graphql:
#    path: ../graphql_dart/angel_graphql
#  graphql_server2:
#    path: ../graphql_dart/graphql_server
#  graphql_parser2:
#    path: ../graphql_dart/graphql_parser
#  angel3_container:
#    path: ../belatuk/packages/container/angel_container

    